version: '3.2'

services:
  search-service:
    image: sofia2021/search-service:latest
    hostname: search-service
    restart: always
    volumes:
      - ../credentials.env:/credentials.env
    ports:
      - "9094:9094"
    labels:
      - "traefik.http.routers.search-service-sofia.rule=Path(`/searchQuestions`) || Path(`/searchAnswers`) || Path(`/searchUsers`) || Path(`/hotlist`) || Path(`/search`)"
    networks:
      - sofia

  qa-service:
    image: sofia2021/qa-service:latest
    hostname: qa-service
    restart: always
    volumes:
      - ../credentials.env:/credentials.env
    ports:
      - "9093:9093"
    labels:
      - "traefik.http.routers.qa-service-sofia.rule=Path(`/questions`) || Path(`/question`) || Path(`/answers`) || Path(`/answer`) || Path(`/comments`) || Path(`/criticisms`)"
    networks:
      - sofia

  users-service:
    image: sofia2021/users-service:latest
    container_name: users-service
    hostname: users-service
    restart: always
    volumes:
      - ../credentials.env:/credentials.env
    ports:
      - "9092:9092"
    labels:
      - "traefik.http.routers.users-service-sofia.rule=Path(`/approve`) || Path(`/ban`) || Path(`/banned`) || Path(`/checkSession`) || Path(`/checkToken`) || Path(`/collection`) || Path(`/favorite`) || Path(`/follow`) || Path(`/followed`) || Path(`/followers`) || Path(`/infoList`) || Path(`/like`) || Path(`/login`) || Path(`/notifications`) || Path(`/oauth/github`) || Path(`/passwd`) || Path(`/publicInfo`) || Path(`/refreshToken`) || Path(`/register`) || Path(`/userAnswers`) || Path(`/userQuestions`) || Path(`/verificationCode`) || Path(`/verify`) || Path(`/wordBan`) || Path(`/wordsBanned`)"
    networks:
      - sofia

  hanlp:
    image: samurais/hanlp-api:1.0.0
    container_name: hanlp
    hostname: hanlp
    restart: always
    ports:
      - "3002:3000"
    networks:
      - sofia

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - sofia

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - sofia

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    ports:
      - "4040:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - sofia

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sofia

  zookeeper-server:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper-server
    hostname: zookeeper-server
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - sofia

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9100:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://172.17.0.2:9100
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper-server
    networks:
      - sofia

  traefik:
    image: traefik:v2.2
    container_name: traefik
    hostname: traefik
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker
      - --accesslog
      - --accesslog.fields.names.StartUTC=drop
      - --metrics.prometheus
      - --tracing.elastic
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: syslog
      options:
        tag: traefik
    environment:
      - TZ=US/Alaska
    networks:
      - sofia

networks:
  sofia:
    driver: bridge
