name: Go

on:
  push:
    branches: [ master, develop, feature-skfe, feature-zhc ]
  pull_request:
    branches: [ master, develop, feature-skfe, feature-zhc ]

jobs:
  qa-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Run Go testing
      working-directory: backend/qa-service
      run: go test ./...
  users-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Run Go testing
      working-directory: backend/users-service
      run: go test ./...
  search-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Run Go testing
      working-directory: backend/search-service
      run: go test ./...
