name: Go

on:
  push:
    branches: [ master, develop, feature-zhc ]
  pull_request:
    branches: [ master, develop, feature-zhc ]

jobs:
  users-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Run Go testing
      working-directory: backend/users-service
      run: go test ./...
